"""Add cascade delete to Review foreign keys

Revision ID: 8921c6d7ffc8
Revises: 5eb1c0219a24
Create Date: 2024-12-31 15:02:19.316347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8921c6d7ffc8'
down_revision = '5eb1c0219a24'
branch_labels = None
depends_on = None

from sqlalchemy.engine.reflection import Inspector

def get_constraint_name_user_id():
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    constraints = inspector.get_foreign_keys('reservations')
    for constraint in constraints:
        if 'user_id' in constraint['constrained_columns']:
            return constraint['name']
    return None


def get_constraint_name_restaurant_id():
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    constraints = inspector.get_foreign_keys('reviews')
    for constraint in constraints:
        if 'restaurant_id' in constraint['constrained_columns']:
            return constraint['name']
    return None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)


    constraint_name_user_id = get_constraint_name_user_id()
    if constraint_name_user_id:
        with op.batch_alter_table('reviews', schema=None) as batch_op:
            batch_op.drop_constraint(constraint_name_user_id, type_='foreignkey')
            batch_op.create_foreign_key(constraint_name_user_id, 'users', ['user_id'], ['id'], ondelete='CASCADE')


    constraint_name_restaurant_id = get_constraint_name_restaurant_id()
    if constraint_name_restaurant_id:
        with op.batch_alter_table('reviews', schema=None) as batch_op:
            batch_op.drop_constraint(constraint_name_restaurant_id, type_='foreignkey')
            batch_op.create_foreign_key(constraint_name_restaurant_id, 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')





    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    constraint_name_user_id = get_constraint_name_user_id()
    if constraint_name_user_id:
        with op.batch_alter_table('reviews', schema=None) as batch_op:
            batch_op.drop_constraint(constraint_name_user_id, type_='foreignkey')
            batch_op.create_foreign_key(constraint_name_user_id, 'users', ['user_id'], ['id'], ondelete='CASCADE')


    constraint_name_restaurant_id = get_constraint_name_restaurant_id()
    if constraint_name_restaurant_id:
        with op.batch_alter_table('reviews', schema=None) as batch_op:
            batch_op.drop_constraint(constraint_name_restaurant_id, type_='foreignkey')
            batch_op.create_foreign_key(constraint_name_restaurant_id, 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')


    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
