"""Add is_preview column to restaurant_image

Revision ID: cbc9738fbe61
Revises: 641f8f6f8486
Create Date: 2025-01-01 22:14:17.555110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc9738fbe61'
down_revision = '641f8f6f8486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_preview', sa.Boolean(), nullable=True))
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_images', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('is_preview')

    # ### end Alembic commands ###
